version: '3'
services:
  zap:
    image: owasp/zap2docker-stable
    volumes:
      - ${PWD}:/zap/wrk/:rw
    user: zap
    ports:
      - 8080:8080
      - 8090:8090
    stdin_open: true
    tty: true
    command: zap-webswing.sh
    
  dvwa:
    image: vulnerables/web-dvwa
    ports:
      - 80:80
    stdin_open: true
    tty: true

  bwapp:
    image: raesene/bwapp
    ports:
      - 9090:80
    stdin_open: true
    tty: true
